---
# rat_hunter Dependabot config file
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
      timezone: "Australia/Melbourne"
      time: "07:00"
    target-branch: "develop"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
      timezone: "Australia/Melbourne"
      time: "07:00"
    target-branch: "develop"
