---
# Github actions workflow file
name: rat_hunter - linting and testing

on:  # yamllint disable rule:truthy
    push:
        branches:
            - main
            - feature/*
        paths-ignore:
            - 'README.md'
            - 'TODO.md'
    pull_request:
        branches:
            - develop
        paths-ignore:
            - 'README.md'
            - 'TODO.md'

jobs:
    build:
        name: Lint and test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.8, 3.9]
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip freeze install
            - name: Run nox lint
              run: nox -s lint
